import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from '@/components/header/header'
import SearchBar from '@/components/searchBar/search'
import Index from '@/components/map/map'
import WeatherMap from '@/components/map/WeatherMap'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  // Coordonnées de Paris
  const parisCoordinates = { lat: 48.8566, lng: 2.3522 };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <SearchBar onSearch={(query: string) => {
        }} />


        <WeatherMap/>
      </main>
    </>
  )
}
